server:
    verbosity: 1
    interface: 0.0.0.0
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes
    num-threads: 2
    cache-min-ttl: 30
    cache-max-ttl: 300
    msg-cache-size: 32m
    rrset-cache-size: 64m

forward-zone:
  name: "."
  forward-addr: 192.168.100.1
  forward-addr: 1.1.1.1
  forward-addr: 8.8.8.8