# eq12_discussions_seed.py
import asyncio
import json
import os
from datetime import UTC, datetime

import aiohttp

TOPICS = [
    ("Week 6 EV Watchlist", "Top +EV edges from opening lines, with bankroll tiers."),
    ("Bankroll 101", "Flat vs Kelly for NFL; when to scale down on correlated legs."),
    ("Live Betting Playbook", "When in-game pace/drive data flips EV in Q3."),
    ("Parlay Pitfalls", "Why mixing spread+total on same game risks correlation bans."),
    ("Model Drift Check", "How we nightly backtest prompts to maintain CLV."),
    ("Arb Hygiene", "Safer ways to capture misprices across DK/FD/MGM."),
    ("Forum Monetization", "Ethical affiliate placement + clear disclaimers."),
    ("Azure vs OpenAI", "Failover and cost profiles in our stack."),
    ("RAG Setup", "Indexing EQ12 docs for grounded answers."),
    ("Cost Guard Rules", "How we cap spend and prevent 429s."),
]


async def post_discussion(title: str, body: str) -> dict:
    token = os.getenv("GH_TOKEN")
    owner = os.getenv("GH_REPO_OWNER")
    repo = os.getenv("GH_REPO_NAME")

    if not token:
        print(f"⚠️ No GH_TOKEN found, skipping: {title}")
        return {"status": "skipped", "reason": "no_token"}

    if not owner or not repo:
        print(f"⚠️ Missing GH_REPO_OWNER/GH_REPO_NAME, skipping: {title}")
        return {"status": "skipped", "reason": "no_repo_config"}

    url = f"https://api.github.com/repos/{owner}/{repo}/discussions"
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "User-Agent": "EQ12-DiscussionSeeder/1.0",
    }

    # Expand body with EQ12 branding and context
    expanded_body = f"""{body}

## 🎯 Discussion Goals

This is part of EQ12's comprehensive betting automation and community intelligence system. We're building:

- **Automated Sports Analysis**: Real-time odds tracking and EV calculations
- **Risk Management**: Kelly criterion and bankroll optimization
- **Community Intelligence**: Crowd-sourced insights and pattern recognition
- **Responsible Gaming**: Clear guidelines and harm reduction

## 🤖 EQ12 Integration

This discussion connects to our automated systems:
- OpenAI API integration for analysis
- Real-time webhook processing
- GitHub Actions for CI/CD
- Production monitoring and alerts

## 💰 Monetization & Compliance

All content includes:
- ✅ Clear affiliate disclosures
- ✅ Responsible gaming warnings
- ✅ "For entertainment purposes only" disclaimers
- ✅ Problem gambling resources

---

**Generated by EQ12 Discussion Seeder at {datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")}**

*Join the conversation and help build the future of automated sports betting intelligence!*"""

    data = {"title": title, "body": expanded_body}

    try:
        async with aiohttp.ClientSession() as s:
            async with s.post(url, headers=headers, json=data) as r:
                result_text = await r.text()
                if r.status == 201:
                    result = json.loads(result_text)
                    print(f"✅ Created: {title} - {result.get('html_url', 'No URL')}")
                    return {
                        "status": "created",
                        "title": title,
                        "url": result.get("html_url"),
                        "id": result.get("id"),
                    }
                else:
                    print(f"❌ Failed: {title} - Status {r.status}: {result_text[:200]}")
                    return {
                        "status": "failed",
                        "title": title,
                        "error": result_text[:500],
                        "status_code": r.status,
                    }
    except Exception as e:
        print(f"❌ Exception for {title}: {e}")
        return {"status": "error", "title": title, "error": str(e)}


async def seed_all_discussions():
    """Seed all discussions and return results summary"""
    print("🚀 Starting EQ12 Discussion Seeding...")

    results = []
    for title, body in TOPICS:
        result = await post_discussion(title, body)
        results.append(result)
        # Rate limiting: pause between requests
        await asyncio.sleep(2)

    # Summary
    created = len([r for r in results if r["status"] == "created"])
    failed = len([r for r in results if r["status"] in ["failed", "error"]])
    skipped = len([r for r in results if r["status"] == "skipped"])

    print("\n📊 Seeding Summary:")
    print(f"✅ Created: {created}")
    print(f"❌ Failed: {failed}")
    print(f"⚠️ Skipped: {skipped}")
    print(f"📝 Total: {len(results)}")

    # Save results to log
    log_file = os.path.join(
        os.getcwd(), "logs", f"discussions_seed_{datetime.now(UTC).strftime('%Y%m%d_%H%M%S')}.json"
    )
    os.makedirs(os.path.dirname(log_file), exist_ok=True)

    with open(log_file, "w", encoding="utf-8") as f:
        json.dump(
            {
                "timestamp": datetime.now(UTC).isoformat(),
                "summary": {"created": created, "failed": failed, "skipped": skipped},
                "results": results,
            },
            f,
            indent=2,
            ensure_ascii=False,
        )

    print(f"📄 Results saved to: {log_file}")
    return results


async def main():
    await seed_all_discussions()


if __name__ == "__main__":
    asyncio.run(main())
