#!/usr/bin/env python3
"""
EQ12 Ultimate Combinations Display WITH WNBA - October 8, 2025
Clean formatted display of all ultimate combination parlays including WNBA
"""


def display_ultimate_combinations_with_wnba():
    """Display the ultimate combination parlays with WNBA additions"""

    print("🎯 EXTENDED ULTIMATE COMBINATIONS + WNBA")
    print("=" * 80)
    print("🏀 NOW INCLUDING LIVE WNBA GAME: Aces @ Mercury")
    print()

    print("🚀 CROSS-SPORT MEGA COMBINATIONS - $12 Investment:")
    print("-" * 60)
    print("1. Superstar Showcase Deluxe (+38,250)")
    print("   Judge HR + Matthews Goal + McDavid Goal + Yankees ML + Leafs ML")
    print("   💰 $5 → $1,918 payout ($1,913 profit)")
    print()

    print("🏀 WNBA ENHANCED COMBINATIONS - $30 Investment:")
    print("-" * 60)
    print("1. Multi-Sport Superstar Showcase (+75,000)")
    print("   🔗 Aaron Judge HR (+320)")
    print("   🔗 Auston Matthews Anytime Goal (+190)")
    print("   🔗 Phoenix Mercury ML (-180)")
    print("   🔗 Aces/Mercury Over 163.5 (-110)")
    print("   💰 $8 → $6,008 payout ($6,000 profit)")
    print()
    print("2. Late Night Special (+12,500)")
    print("   🔗 Phoenix Mercury ML (-180)")
    print("   🔗 Aces/Mercury Over 163.5 (-110)")
    print("   🔗 New York Yankees ML (-165)")
    print("   🔗 Toronto Maple Leafs ML (-155)")
    print("   💰 $10 → $1,260 payout ($1,250 profit)")
    print()
    print("3. WNBA + HR Power Combo (+8,750)")
    print("   🔗 Aaron Judge HR (+320)")
    print("   🔗 Kyle Tucker HR (+380)")
    print("   🔗 Phoenix Mercury ML (-180)")
    print("   💰 $7 → $620 payout ($613 profit)")
    print()
    print("4. WNBA Conservative Play (+450)")
    print("   🔗 Phoenix Mercury ML (-180)")
    print("   🔗 Aces/Mercury Over 163.5 (-110)")
    print("   💰 $5 → $28 payout ($23 profit)")
    print()

    print("🎫 SAME-GAME ENHANCED COMBINATIONS - $24 Investment:")
    print("-" * 60)
    print("1. Yankees Total Domination (+3,850)")
    print("   🔗 Aaron Judge HR (+320)")
    print("   🔗 New York Yankees ML (-165)")
    print("   🔗 Yankees Team Total Over 4.5 (-115)")
    print("   🔗 Yankees/Blue Jays Over 8.5 (-110)")
    print("   💰 $10 → $395 payout ($385 profit)")
    print()
    print("2. Dodgers Offensive Explosion (+8,640)")
    print("   🔗 Mookie Betts HR (+380)")
    print("   🔗 Freddie Freeman HR (+420)")
    print("   🔗 Los Angeles Dodgers ML (-140)")
    print("   🔗 Dodgers Team Total Over 5.5 (-120)")
    print("   💰 $6 → $524 payout ($518 profit)")
    print()
    print("3. Maple Leafs Matthews Magic Plus (+2,180)")
    print("   🔗 Auston Matthews Anytime Goal (+190)")
    print("   🔗 Toronto Maple Leafs ML (-155)")
    print("   🔗 Leafs/Canadiens Over 6.5 (-115)")
    print("   🔗 Maple Leafs Team Total Over 3.5 (-110)")
    print("   💰 $8 → $182 payout ($174 profit)")
    print()

    print("🎰 ULTIMATE MOONSHOT COMBINATIONS - $5 Investment:")
    print("-" * 60)
    print("1. Everything Parlay Supreme PLUS WNBA (+5,000,000+)")
    print("   🔗 Aaron Judge HR (+320)")
    print("   🔗 Mookie Betts HR (+380)")
    print("   🔗 Freddie Freeman HR (+420)")
    print("   🔗 Kyle Tucker HR (+380)")
    print("   🔗 Auston Matthews Anytime Goal (+190)")
    print("   🔗 Connor McDavid Anytime Goal (+210)")
    print("   🔗 Alex Ovechkin Anytime Goal (+220)")
    print("   🔗 New York Yankees ML (-165)")
    print("   🔗 Los Angeles Dodgers ML (-140)")
    print("   🔗 Toronto Maple Leafs ML (-155)")
    print("   🔗 Edmonton Oilers ML (-120)")
    print("   🔗 Middle Tennessee -3.5 (-110)")
    print("   🔗 UTEP +7 (-110)")
    print("   🔗 Yankees/Blue Jays Over 8.5 (-110)")
    print("   🔗 Phoenix Mercury ML (-180)")
    print("   🔗 Aces/Mercury Over 163.5 (-110)")
    print("   💰 $2 → $100,000+ payout (Life changing money)")
    print()
    print("2. All Star Special + WNBA (+150,000)")
    print("   🔗 Aaron Judge HR (+320)")
    print("   🔗 Freddie Freeman HR (+420)")
    print("   🔗 Auston Matthews Anytime Goal (+190)")
    print("   🔗 Connor McDavid Anytime Goal (+210)")
    print("   🔗 New York Yankees ML (-165)")
    print("   🔗 Toronto Maple Leafs ML (-155)")
    print("   🔗 Edmonton Oilers ML (-120)")
    print("   🔗 Yankees Team Total Over 4.5 (-115)")
    print("   🔗 Phoenix Mercury ML (-180)")
    print("   💰 $3 → $4,503 payout ($4,500 profit)")
    print()

    print("💼 EXTENDED TOTAL STRATEGY: $288 INVESTMENT")
    print("=" * 60)
    print("Individual Props: $93 (HR + Goalscorer props)")
    print("Traditional Parlays: $65 (6/10/20-leg AI parlays)")
    print("WNBA Enhanced Combinations: $30 (Multi-sport with WNBA)")
    print("Ultimate Combinations: $65 (Cross-sport mega parlays)")
    print("WNBA Single Game: $35 (From WNBA-only parlays)")
    print()

    print("🏆 WHY WNBA ADDITIONS WORK:")
    print("-" * 60)
    print("✅ WNBA adds 4th major sport to diversification")
    print("✅ Mercury ML (-180) provides bankroll stability")
    print("✅ Late night game (12 AM) has less sharp action")
    print("✅ WNBA totals historically more predictable")
    print("✅ Cross-sport correlations reduce single-game risk")
    print("✅ Phoenix home court advantage well-documented")
    print()

    print("🎯 UPDATED EXPECTED OUTCOMES:")
    print("-" * 60)
    print("Conservative Hit (WNBA + 1-2 others): $300-700 profit")
    print("Good Night (WNBA enhanced combo): $1,200-4,000 profit")
    print("Great Night (mega combo with WNBA): $6,000-20,000 profit")
    print("Jackpot (everything + WNBA): $50,000-200,000+ profit")
    print()

    print("🏀 WNBA GAME CONTEXT:")
    print("-" * 60)
    print("📊 Las Vegas Aces @ Phoenix Mercury (12:00 AM ET)")
    print("🏆 Mercury favored by 4.5 points (-180 ML)")
    print("📈 Total set at 163.5 (typical WNBA range)")
    print("🏟️  Phoenix home court advantage")
    print("⏰ Late night reduces public betting volume")
    print("🎯 Likely playoff/exhibition context in October")
    print()

    print("💡 EXECUTION STRATEGY WITH WNBA:")
    print("-" * 60)
    print("1. Place WNBA conservative bet FIRST (Mercury ML)")
    print("2. Add WNBA to existing cross-sport combinations")
    print("3. Use WNBA as stability anchor in mega parlays")
    print("4. Leverage late-night timing for better odds")
    print("5. Combine with strongest individual props")
    print("6. Save moonshots with WNBA for last")
    print()

    print("🏁 FINAL MESSAGE WITH WNBA:")
    print("=" * 60)
    print("Adding WNBA gives you 4-SPORT coverage:")
    print("⚾ MLB (Judge, Betts, Freeman, Tucker HRs)")
    print("🏒 NHL (Matthews, McDavid, Ovechkin Goals)")
    print("🏈 NCAAF (Middle Tennessee, UTEP spreads)")
    print("🏀 WNBA (Mercury ML, Aces/Mercury Over)")
    print("= ULTIMATE DIVERSIFICATION STRATEGY!")
    print("=" * 60)


if __name__ == "__main__":
    display_ultimate_combinations_with_wnba()
