<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EQ12.CI</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EQ12.Core\EQ12.Core.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Roslyn.Diagnostics.Analyzers" Version="3.3.4" />
  </ItemGroup>

</Project>
