<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>EQ12.StackAgent</RootNamespace>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EQ12.Core\EQ12.Core.vbproj" />
    <ProjectReference Include="..\EQ12.Diagnostics\EQ12.Diagnostics.vbproj" />
    <ProjectReference Include="..\EQ12.BICore\EQ12.BICore.vbproj" />
  </ItemGroup>

</Project>
