#!/bin/bash
# EQ12 Dev Container Setup Script
# Purpose: Complete VB debugging and development environment setup
# Usage: Automatically run by devcontainer.json postCreateCommand

set -e

echo "🚀 EQ12 Advanced Development Container Setup Starting..."
echo "=================================================="

# Update system packages
echo "📦 Updating system packages..."
apt-get update && apt-get upgrade -y

# Install VB.NET and Mono for VB development
echo "🔧 Installing VB.NET and Mono development tools..."
apt-get install -y \
    mono-complete \
    mono-vbnc \
    mono-mcs \
    mono-debugger \
    nuget

# Install additional development tools
echo "🛠️ Installing additional development tools..."
apt-get install -y \
    curl \
    wget \
    jq \
    tree \
    htop \
    vim \
    nano \
    zip \
    unzip

# Install Python debugging and quality tools
echo "🐍 Setting up Python development environment..."
python3 -m pip install --upgrade pip
python3 -m pip install \
    pytest \
    black \
    flake8 \
    mypy \
    pylint \
    coverage \
    pytest-cov \
    requests \
    beautifulsoup4 \
    selenium \
    playwright

# Install Playwright browsers
echo "🌐 Installing Playwright browsers..."
python3 -m playwright install

# Install Node.js development tools
echo "📦 Setting up Node.js development environment..."
npm install -g \
    typescript \
    eslint \
    prettier \
    nodemon \
    pm2

# Create EQ12 workspace structure
echo "📁 Setting up EQ12 workspace structure..."
cd /workspaces/EQ12

# Ensure all required directories exist
mkdir -p logs
mkdir -p vb_projects
mkdir -p dotnet_tools
mkdir -p data
mkdir -p configs
mkdir -p dashboard

# Set up VB debugging environment
echo "🔧 Configuring VB debugging environment..."
if [ -f "scripts/eq12_vb_debugging_system.py" ]; then
    echo "✅ VB debugging system found"
    # Test the VB debugging system
    python3 scripts/eq12_vb_debugging_system.py --help > /dev/null 2>&1 && \
    echo "✅ VB debugging system is functional" || \
    echo "⚠️ VB debugging system needs attention"
else
    echo "⚠️ VB debugging system not found - may need to be created"
fi

# Configure Git for signed commits
echo "🔐 Configuring Git for signed commits..."
git config --global commit.gpgsign true
git config --global user.signingkey "$(gpg --list-secret-keys --keyid-format LONG | grep sec | head -1 | cut -d'/' -f2 | cut -d' ' -f1)" || true

# Set up .NET development environment
echo "⚙️ Setting up .NET development environment..."
dotnet --version && echo "✅ .NET SDK is available" || echo "⚠️ .NET SDK not found"

# Install additional .NET templates
dotnet new --install Microsoft.DotNet.Web.ProjectTemplates
dotnet new --install Microsoft.AspNetCore.SpaTemplates

# Create symbolic links for easier access
echo "🔗 Creating convenience symbolic links..."
ln -sf /workspaces/EQ12/scripts/eq12_vb_debugging_wrapper.ps1 /usr/local/bin/vb-debug || true
ln -sf /workspaces/EQ12/scripts/eq12_flake8_autofix.py /usr/local/bin/flake8-fix || true

# Set up PowerShell environment
echo "💠 Setting up PowerShell environment..."
# Install PowerShell modules if available
pwsh -NoProfile -Command "
    Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser -Force
    if (Get-Module -ListAvailable -Name Pester) { 
        Write-Host '✅ Pester module available' 
    } else { 
        Write-Host '⚠️ Pester module not available' 
    }
" 2>/dev/null || echo "⚠️ PowerShell setup had issues"

# Create VB project template
echo "📝 Creating VB project template..."
cat > vb_projects/EQ12_VB_Template.vb << 'EOF'
Option Strict On
Option Explicit On

' EQ12 VB Template with Hardcoded Debugging Best Practices
' Generated by EQ12 Dev Container Setup
' Includes: Option enforcement, Debug logging, Error handling

Imports System

Public Class EQ12VBTemplate
    
    Public Shared Sub Main()
        Debug.WriteLine("🚀 EQ12 VB Template starting: " & DateTime.Now.ToString())
        
        Try
            ' Your application logic here
            Dim result As String = ProcessData("sample_input")
            Debug.WriteLine("📊 Processing result: " & result)
            
        Catch ex As Exception
            Debug.WriteLine("❌ Exception in Main: " & ex.Message)
            Debug.WriteLine("📊 Stack trace: " & ex.StackTrace)
        Finally
            Debug.WriteLine("✅ EQ12 VB Template completed: " & DateTime.Now.ToString())
        End Try
    End Sub
    
    Private Shared Function ProcessData(input As String) As String
        Debug.WriteLine("🔍 Entering ProcessData: " & DateTime.Now.ToString())
        Debug.WriteLine("📊 Input parameter: " & input)
        
        If String.IsNullOrEmpty(input) Then
            Debug.WriteLine("⚠️ Empty input detected")
            Return "ERROR_EMPTY_INPUT"
        End If
        
        Dim result As String = input.ToUpper()
        Debug.WriteLine("📊 Processed result: " & result)
        Debug.WriteLine("✅ Exiting ProcessData: " & DateTime.Now.ToString())
        
        Return result
    End Function
    
End Class
EOF

# Set permissions
echo "🔒 Setting file permissions..."
chmod +x scripts/*.py 2>/dev/null || true
chmod +x scripts/*.ps1 2>/dev/null || true

# Create workspace info file
echo "📋 Creating workspace information..."
cat > EQ12_CONTAINER_INFO.md << EOF
# EQ12 Development Container Information

**Container Image**: mcr.microsoft.com/dotnet/sdk:8.0  
**Setup Date**: $(date)  
**VB Debugging**: Enabled  
**Python Version**: $(python3 --version)  
**Node.js Version**: $(node --version)  
**PowerShell Version**: $(pwsh --version)  
**.NET Version**: $(dotnet --version)  

## Available Tools

- **VB Debugging System**: /workspaces/EQ12/scripts/eq12_vb_debugging_system.py
- **Flake8 Auto-fix**: /workspaces/EQ12/scripts/eq12_flake8_autofix.py  
- **GitLeaks Guardian**: /workspaces/EQ12/scripts/eq12_gitleaks_guardian.py
- **Script Integrity Suite**: /workspaces/EQ12/scripts/eq12_script_integrity_suite.ps1

## Quick Commands

\`\`\`bash
# VB debugging - enforce all best practices
python3 scripts/eq12_vb_debugging_system.py --enforce-all

# Python code quality
python3 scripts/eq12_flake8_autofix.py --workspace /workspaces/EQ12 --fix-all

# Security scan
python3 scripts/eq12_gitleaks_guardian.py --action comprehensive

# Test all systems
pytest tests/ -v
\`\`\`

## VS Code Tasks Available

- EQ12: VB Debugging - Enforce All
- EQ12: VB Debugging - Process Current File  
- EQ12: Complete VB Development Suite
- EQ12: Complete Security Scan
- EQ12: Enhanced Flake8 Auto-Fix

Use Ctrl+Shift+P -> "Tasks: Run Task" to access these.
EOF

# Final status check
echo ""
echo "🎉 EQ12 Development Container Setup Complete!"
echo "=================================================="
echo "✅ System packages updated"
echo "✅ VB.NET and Mono installed"
echo "✅ Python development environment ready"
echo "✅ Node.js development environment ready"
echo "✅ PowerShell environment configured"
echo "✅ .NET SDK available"
echo "✅ VB debugging system ready"
echo "✅ Workspace structure created"
echo "✅ Development tools installed"
echo ""
echo "📋 See EQ12_CONTAINER_INFO.md for usage information"
echo "🚀 Ready for advanced VB debugging and development!"