feeds:
  - https://www.espn.com/espn/rss/nba/news
  - https://www.cbssports.com/rss/headlines/nba/
  - https://sports.yahoo.com/nba/rss/
  - https://www.rotowire.com/rss/news.php?sport=NBA
  - https://basketball.realgm.com/rss/wiretap/0/0.xml
  - https://www.hoopsrumors.com/feed
  - https://www.nba.com/news/rss.xml
  - https://www.si.com/rss/nba.xml
  - https://www.theringer.com/rss/nba.xml
  - https://www.blazersedge.com/rss/current
  - https://www.brewhoop.com/rss/current