# cleaned candidate generated by create_cleaned_candidate.py

# [noise removed] $ROOT = "C:\EQ12\EdgeGodParlays"
# [noise removed] $BOT  = Join-Path $ROOT "ai_betting_bot_stealth_final_flask_pro.py"
# [noise removed] Copy-Item $BOT "$BOT.bak" -Force
# [noise removed]
# [noise removed] # Read, then replace the webhook + self_test sections and add the import + new helper
# [noise removed] $code = Get-Content $BOT -Raw
# [noise removed]
# [noise removed] # Ensure import line present
# [noise removed] if ($code -notmatch 'from sports_live import context_for_command') {
# [noise removed]   $code = $code -replace 'from flask import Flask, request',
# [noise removed]     'from flask import Flask, request' + "`r`nfrom sports_live import context_for_command"
# [noise removed] }
# [noise removed]
# [noise removed] # Replace chatgpt() call site inside webhook to prepend context/guardrails
# [noise removed] $code = $code -replace '(elif text.startswith\("/"\):)([\s\S]*?)return "OK", 200', @'
# [noise removed] elif text.startswith("/"):
    key = text[1:]
    instruction = LOGIC.get(key, None)
# [noise removed]
# [noise removed]     # Build sport-specific context and guardrails
# [noise removed]     sport, ctx = context_for_command(key)
    guard = ""
# [noise removed]     if sport == "mlb":
        guard = (
# [noise removed]             "RULES: Only use MLB teams/players from TODAY. "
# [noise removed]             "Reject colleges/soccer/hypotheticals. No NBA/NCAA/NHL. "
# [noise removed]             "If player uncertain, pick from listed MLB games only.\n"
# [noise removed]         )
# [noise removed]     elif sport == "wnba":
        guard = (
# [noise removed]             "RULES: Only use WNBA teams/players from TODAY. "
# [noise removed]             "No NBA, NCAA, or men’s teams. Keep props strictly POINTS-only.\n"
# [noise removed]         )
# [noise removed]     elif sport == "ufc":
        guard = (
# [noise removed]             "RULES: Only UFC fighters on active/scheduled cards. "
# [noise removed]             "Picks must be Method of Victory (KO/TKO/SUB/DEC) with short rationale.\n"
# [noise removed]         )
# [noise removed]     elif sport == "boxing":
        guard = (
# [noise removed]             "RULES: Only sanctioned boxing bouts; prefer distance/decision or KO props with compubox trends.\n"
# [noise removed]         )
# [noise removed]
# [noise removed]     if instruction:
        prompt = (
# [noise removed]             f"{instruction}\n\n"
# [noise removed]             f"{guard}"
# [noise removed]             f"{ctx}\n"
# [noise removed]             "Constrain picks exclusively to the teams/fighters above. "
# [noise removed]             "If no valid games today, say so briefly."
# [noise removed]         )
        ans = chatgpt(prompt, chat_id)
# [noise removed]         tg_send(f"📊 *{key.upper()}*\n{ans}", chat_id)
# [noise removed]     else:
# [noise removed]         tg_send("⚠️ Unknown command. Try /commands.", chat_id)
# [noise removed]     return "OK", 200
# [noise removed] '@
# [noise removed]
# [noise removed] # Make self_test prints ASCII-only & tolerant
# [noise removed] $code = $code -replace 'print\(".*Local /health responded OK".*\)', 'print("Local /health responded OK")'
# [noise removed] $code = $code -replace 'print\(f".*Self-test failed:.*"\)', 'print("Self-test failed")'
# [noise removed]
# [noise removed] Set-Content -Path $BOT -Value $code -Encoding UTF8 -Force
# [noise removed] Write-Host "✅ Patched $BOT (context + guardrails + ASCII self_test)"
# [noise removed]
# [noise removed] # Restart cleanly and set webhook to current ngrok tunnel
# [noise removed] netstat -ano | findstr ":5005" | ForEach-Object {
# [noise removed]   $p = ($_ -split "\s+")[-1]; if ($p -match '^\d+$') { try { Stop-Process -Id $p -Force -EA SilentlyContinue } catch {} }
# [noise removed] }
# [noise removed] Get-Process python,ngrok -EA SilentlyContinue | Stop-Process -Force -EA SilentlyContinue
# [noise removed] C:\EQ12\EdgeGodParlays\Start-EdgeGodParlays.ps1
# [noise removed]
# [noise removed] # Wait and show health + current commands
# [noise removed] Start-Sleep -Seconds 4
# [noise removed] Invoke-WebRequest -UseBasicParsing http://127.0.0.1:5005/health | Select-Object -ExpandProperty Content