import logging
import re
from pathlib import Path

# Set up logging
logger = logging.getLogger(__name__)

# create_cleaned_candidate.py
# Conservative extractor to produce a cleaned candidate Python file suitable for compilation.
# Strategy:
# - Keep imports and 'from ... import ...'
# - Keep top-level assignments like NAME = value
# - Keep def/class declarations and their indented bodies
# - Keep if __name__ == '__main__' blocks and their indented bodies
# - Comment out any lines that look like PowerShell or other noise
# Writes ai_betting_bot_stealth_final_flask_pro.py.merged-candidate.cleaned.py

orig = Path(r"C:/EQ12/EdgeGodParlays/ai_betting_bot_stealth_final_flask_pro.py.merged-candidate.py")
out = orig.with_suffix(".cleaned.py")
if not orig.exists():
    print("ERROR: original not found", orig)
    raise SystemExit(1)
text = orig.read_bytes()
if text.startswith(b"\xef\xbb\xbf"):
    text = text[3:]
s = text.decode("utf-8", errors="replace")
lines = s.splitlines()

import_pat = re.compile(r"^\s*(import\b|from\b)")
def_pat = re.compile(r"^\s*def\b")
class_pat = re.compile(r"^\s*class\b")
assign_pat = re.compile(r"^\s*[A-Za-z_][A-Za-z0-9_]*\s*=")
main_pat = re.compile(r"^\s*if\s+__name__\s*==\s*['\"]__main__['\"]\s*:")

ps_noise = re.compile(
    r"\$|Copy-Item|Move-Item|Start-Process|New-Item|Set-Alias|Register-ScheduledTask|Import-Module|`|@\"|@'|\'@|\"@|-replace|-match|\bGet-ChildItem\b"
)

out_lines = ["# cleaned candidate generated by create_cleaned_candidate.py\n"]
i = 0
n = len(lines)
while i < n:
    ln = lines[i]
    if import_pat.match(ln) and not ps_noise.search(ln):
        out_lines.append(ln)
        i += 1
        continue
    if def_pat.match(ln) or class_pat.match(ln):
        # copy the def/class and its indented body
        out_lines.append(ln)
        i += 1
        while i < n and (
            lines[i].startswith("    ") or lines[i].startswith("\t") or lines[i].strip() == ""
        ):
            out_lines.append(lines[i])
            i += 1
        continue
    if main_pat.match(ln):
        out_lines.append(ln)
        i += 1
        while i < n and (
            lines[i].startswith("    ") or lines[i].startswith("\t") or lines[i].strip() == ""
        ):
            out_lines.append(lines[i])
            i += 1
        continue
    if assign_pat.match(ln) and not ps_noise.search(ln):
        out_lines.append(ln)
        i += 1
        continue
    # otherwise comment out the line
    out_lines.append("# [noise removed] " + ln)
    i += 1

out.write_text("\n".join(out_lines), encoding="utf-8")
print("WROTE cleaned candidate to", out)

# attempt compile
import py_compile

try:
    py_compile.compile(str(out), doraise=True)
    print("PY_COMPILE cleaned: OK")
except Exception as e:
    print("PY_COMPILE cleaned: FAILED")
    logger.info(e)
    raise SystemExit(2)
