#!/usr/bin/env python3
"""
EQ12 Telegram Alert System
Sends real-time notifications for optimal parlay opportunities
"""

import asyncio
import json
import logging
import os
import sys
from dataclasses import asdict, dataclass
from datetime import UTC, datetime
from typing import Any

import requests

# Simple math functions for parlay calculations


def calculate_parlay_odds(decimal_odds_list: list[float]) -> float:
    """Calculate combined decimal odds for independent parlay"""
    result = 1.0
    for odds in decimal_odds_list:
        result *= odds
    return result


def calculate_expected_value(stake: float, odds: float, true_prob: float) -> float:
    """Calculate expected value of a bet"""
    return (stake * odds * true_prob) - stake


@dataclass
class ParlayAlert:
    """Parlay alert data structure"""

    parlay_legs: list[dict[str, Any]]
    total_odds: float
    roi_multiplier: float
    stake_amount: float
    potential_return: float
    expected_value: float
    confidence_score: float
    timestamp: str
    alert_id: str


class TelegramAlerter:
    """Sends parlay alerts via Telegram Bot API"""

    def __init__(self):
        self.bot_token = os.getenv("TELEGRAM_BOT_TOKEN")
        self.chat_id = os.getenv("TELEGRAM_CHAT_ID")
        self.logger = self._setup_logging()

        if not self.bot_token or not self.chat_id:
            raise ValueError(
                "Missing TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID environment variables")

    def _setup_logging(self) -> logging.Logger:
        """Setup logging configuration"""
        logger = logging.getLogger(__name__)
        logger.setLevel(logging.INFO)

        if not logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
            handler.setFormatter(formatter)
            logger.addHandler(handler)

        return logger

    async def send_parlay_alert(self, alert: ParlayAlert) -> bool:
        """Send parlay alert to Telegram"""
        try:
            message = self._format_parlay_message(alert)
            return await self._send_telegram_message(message)
        except Exception as e:
            self.logger.error(f"Failed to send parlay alert: {e}")
            return False

    def _format_parlay_message(self, alert: ParlayAlert) -> str:
        """Format parlay data into Telegram message"""
        emoji_map = {"high": "🔥", "medium": "⚡", "low": "📊"}

        # Determine alert level based on ROI
        if alert.roi_multiplier >= 15:
            level = "high"
        elif alert.roi_multiplier >= 10:
            level = "medium"
        else:
            level = "low"

        emoji = emoji_map[level]

        message = f"{emoji} **EQ12 OPTIMAL PARLAY ALERT** {emoji}\n\n"
        message += f"🎯 **ROI Multiplier:** {alert.roi_multiplier:.1f}x\n"
        message += (
            f"💰 **Stake:** ${alert.stake_amount:.0f} → **Return:** "
            f"${alert.potential_return:.0f}\n"
        )
        message += f"📈 **Expected Value:** ${alert.expected_value:.2f}\n"
        message += f"🎲 **Confidence:** {alert.confidence_score:.1f}%\n\n"

        message += "🏈 **PARLAY LEGS:**\n"
        for i, leg in enumerate(alert.parlay_legs, 1):
            message += f"{i}. {leg['team']} {leg['bet_type']}\n"
            message += f"   Odds: {leg['odds']:+.0f} | Line: {leg.get('line', 'N/A')}\n"

        message += f"\n⏰ **Alert Time:** {alert.timestamp}\n"
        message += f"🆔 **Alert ID:** {alert.alert_id[:8]}\n"
        message += "\n*Generated by EQ12 Live Parlay Scanner*"

        return message

    async def _send_telegram_message(self, message: str) -> bool:
        """Send message via Telegram Bot API"""
        url = f"https://api.telegram.org/bot{self.bot_token}/sendMessage"

        payload = {
            "chat_id": self.chat_id,
            "text": message,
            "parse_mode": "Markdown",
            "disable_web_page_preview": True,
        }

        try:
            async with aiohttp.ClientSession() as session:
                async with session.post(url, json=payload) as response:
                    if response.status == 200:
                        self.logger.info("Parlay alert sent successfully")
                        return True
                    else:
                        error_text = await response.text()
                        self.logger.error(
                            f"Telegram API error {
                                response.status}: {error_text}")
                        return False
        except Exception as e:
            self.logger.error(f"Network error sending Telegram message: {e}")
            return False

    async def send_system_status(self, status_type: str = "startup") -> bool:
        """Send system status notification"""
        status_messages = {
            "startup": (
                "🚀 EQ12 Live Parlay Scanner is now active and monitoring "
                "for optimal opportunities!"),
            "shutdown": "⏹️ EQ12 Live Parlay Scanner has stopped monitoring.",
            "error": (
                "⚠️ EQ12 Live Parlay Scanner encountered an error and may "
                "need attention."),
            "health": (
                "✅ EQ12 Live Parlay Scanner health check - all systems "
                "operational."),
        }

        message = status_messages.get(
            status_type, f"📊 EQ12 System Status: {status_type}")
        message += f"\n\n⏰ Time: {datetime.now(UTC).isoformat()}"

        return await self._send_telegram_message(message)

    async def test_connection(self) -> bool:
        """Test Telegram bot connection"""
        test_message = "🔧 EQ12 Telegram Alert Test - Connection successful!"
        return await self._send_telegram_message(test_message)


class ParlayAlertManager:
    """Manages parlay alert generation and sending"""

    def __init__(self):
        self.alerter = TelegramAlerter()
        self.logger = self._setup_logging()
        self.sent_alerts: set = set()  # Track sent alerts to avoid duplicates

    def _setup_logging(self) -> logging.Logger:
        """Setup logging configuration"""
        logger = logging.getLogger(f"{__name__}.manager")
        logger.setLevel(logging.INFO)

        if not logger.handlers:
            handler = logging.StreamHandler()
            formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
            handler.setFormatter(formatter)
            logger.addHandler(handler)

        return logger

    def create_parlay_alert(
        self,
        parlay_legs: list[dict[str, Any]],
        stake_amount: float = 8.0,
        min_roi_multiplier: float = 10.0,
    ) -> ParlayAlert | None:
        """Create parlay alert from legs data"""
        try:
            # Calculate parlay odds
            odds = [leg["decimal_odds"] for leg in parlay_legs]
            total_odds = calculate_parlay_odds(odds)
            potential_return = stake_amount * total_odds
            roi_multiplier = potential_return / stake_amount

            # Skip if doesn't meet minimum ROI
            if roi_multiplier < min_roi_multiplier:
                return None

            # Calculate expected value (assuming fair market odds)
            true_prob = 1.0 / total_odds  # Convert odds to probability
            expected_value = calculate_expected_value(
                stake_amount, total_odds, true_prob)

            # Calculate confidence score based on various factors
            confidence_score = self._calculate_confidence(parlay_legs, total_odds)

            # Generate unique alert ID
            alert_id = self._generate_alert_id(parlay_legs)

            # Skip if already sent
            if alert_id in self.sent_alerts:
                return None

            alert = ParlayAlert(
                parlay_legs=parlay_legs,
                total_odds=total_odds,
                roi_multiplier=roi_multiplier,
                stake_amount=stake_amount,
                potential_return=potential_return,
                expected_value=expected_value,
                confidence_score=confidence_score,
                timestamp=datetime.now(UTC).isoformat(),
                alert_id=alert_id,
            )

            return alert

        except Exception as e:
            self.logger.error(f"Error creating parlay alert: {e}")
            return None

    def _calculate_confidence(
            self, parlay_legs: list[dict[str, Any]], total_odds: float) -> float:
        """Calculate confidence score for parlay"""
        base_confidence = 70.0

        # Adjust for number of legs (more legs = lower confidence)
        leg_penalty = (len(parlay_legs) - 2) * 5.0
        confidence = base_confidence - leg_penalty

        # Adjust for total odds (very high odds = lower confidence)
        if total_odds > 20:
            odds_penalty = (total_odds - 20) * 0.5
            confidence -= min(odds_penalty, 20.0)

        # Adjust for leg quality (hypothetical scoring)
        for leg in parlay_legs:
            if leg.get("line_movement", 0) > 0:  # Favorable line movement
                confidence += 2.0
            if leg.get("sharp_money", False):  # Sharp money indicator
                confidence += 3.0

        return max(min(confidence, 95.0), 10.0)  # Clamp between 10-95%

    def _generate_alert_id(self, parlay_legs: list[dict[str, Any]]) -> str:
        """Generate unique ID for parlay alert"""
        import hashlib

        # Create hash from parlay legs
        legs_str = json.dumps(
            sorted([f"{leg['team']}_{leg['bet_type']}_{leg['odds']}" for leg in parlay_legs])
        )

        return hashlib.md5(legs_str.encode()).hexdigest()

    async def send_alert(self, alert: ParlayAlert) -> bool:
        """Send parlay alert via Telegram"""
        try:
            success = await self.alerter.send_parlay_alert(alert)
            if success:
                self.sent_alerts.add(alert.alert_id)
                self.logger.info(f"Parlay alert sent: {alert.roi_multiplier:.1f}x ROI")

                # Save alert to log file
                await self._log_alert(alert)

            return success

        except Exception as e:
            self.logger.error(f"Failed to send alert: {e}")
            return False

    async def _log_alert(self, alert: ParlayAlert) -> None:
        """Save alert data to log file"""
        try:
            log_dir = os.path.join(os.path.dirname(os.path.dirname(__file__)), "logs")
            os.makedirs(log_dir, exist_ok=True)

            log_file = os.path.join(log_dir, "parlay_alerts.json")

            # Read existing alerts
            alerts_data = []
            if os.path.exists(log_file):
                with open(log_file) as f:
                    alerts_data = json.load(f)

            # Add new alert
            alerts_data.append(asdict(alert))

            # Keep only last 100 alerts
            alerts_data = alerts_data[-100:]

            # Write back to file
            with open(log_file, "w") as f:
                json.dump(alerts_data, f, indent=2, default=str)

        except Exception as e:
            self.logger.error(f"Failed to log alert: {e}")


async def test_telegram_integration():
    """Test Telegram integration"""
    try:
        print("🧪 Testing EQ12 Telegram Integration...")

        # Test bot connection
        alerter = TelegramAlerter()
        print("📱 Testing bot connection...")

        connection_ok = await alerter.test_connection()
        if not connection_ok:
            print("❌ Bot connection failed!")
            return False

        print("✅ Bot connection successful!")

        # Test parlay alert
        print("📊 Testing parlay alert...")

        # Sample parlay data
        sample_parlay = [
            {
                "team": "Denver Broncos",
                "bet_type": "+4.5",
                "odds": 110,
                "decimal_odds": 2.10,
                "line": "+4.5",
            },
            {
                "team": "Game Total",
                "bet_type": "Over 47.5",
                "odds": -105,
                "decimal_odds": 1.95,
                "line": "47.5",
            },
            {
                "team": "Golden State Warriors",
                "bet_type": "-2.5",
                "odds": -110,
                "decimal_odds": 1.91,
                "line": "-2.5",
            },
        ]

        manager = ParlayAlertManager()
        alert = manager.create_parlay_alert(
            sample_parlay, stake_amount=8.0, min_roi_multiplier=5.0)

        if alert:
            alert_sent = await manager.send_alert(alert)
            if alert_sent:
                print("✅ Parlay alert sent successfully!")
                return True
            else:
                print("❌ Failed to send parlay alert!")
                return False
        else:
            print("❌ Failed to create parlay alert!")
            return False

    except Exception as e:
        print(f"❌ Test failed: {e}")
        return False


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="EQ12 Telegram Alert System")
    parser.add_argument("--test", action="store_true", help="Test Telegram integration")
    parser.add_argument(
        "--status",
        choices=["startup", "shutdown", "error", "health"],
        help="Send system status notification",
    )

    args = parser.parse_args()

    async def main():
        if args.test:
            success = await test_telegram_integration()
            sys.exit(0 if success else 1)

        elif args.status:
            alerter = TelegramAlerter()
            success = await alerter.send_system_status(args.status)
            print(f"Status notification sent: {'✅' if success else '❌'}")

        else:
            print("EQ12 Telegram Alert System")
            print("Use --test to test integration or --status to send status updates")

    asyncio.run(main())
