#!/usr/bin/env python3
"""
EQ12 Performance Monitor - Automated system performance monitoring
Generated by EQ12 Master System Fixer
"""

import json
import os
from datetime import datetime
from pathlib import Path

import psutil


def monitor_eq12_performance():
    eq12_logs = Path(
        os.environ.get(
            "EQ12_LOGS_DIR",
            Path(__file__).resolve().parents[1] / "logs",
        )
    )
    eq12_logs.mkdir(parents=True, exist_ok=True)
    disk_target = eq12_logs.resolve().anchor or str(eq12_logs.resolve())

    # Get system metrics
    cpu_percent = psutil.cpu_percent(interval=1)
    memory = psutil.virtual_memory()
    disk = psutil.disk_usage(disk_target)

    # Count log files by category
    log_counts = {}
    for log_file in eq12_logs.glob("*.log"):
        category = "miscellaneous"
        name = log_file.name.lower()

        if "nfl" in name or "parlay" in name:
            category = "sports_betting"
        elif "chrome" in name or "firefox" in name:
            category = "browser_automation"
        elif "security" in name:
            category = "security"
        elif "error" in name:
            category = "errors"

        log_counts[category] = log_counts.get(category, 0) + 1

    # Performance report
    report = {
        "timestamp": datetime.now().isoformat(),
        "system": {
            "cpu_percent": cpu_percent,
            "memory_percent": memory.percent,
            "memory_available_gb": memory.available / (1024**3),
            "disk_free_gb": disk.free / (1024**3),
        },
        "log_files": log_counts,
        "total_log_files": sum(log_counts.values()),
        "health_status": "good" if sum(log_counts.values()) < 100 else "warning",
    }

    # Save report
    report_file = eq12_logs / \
        f"performance_monitor_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"
    with open(report_file, "w") as f:
        json.dump(report, f, indent=2)

    print(f"Performance report saved: {report_file}")
    return report


if __name__ == "__main__":
    monitor_eq12_performance()
