#!/usr/bin/env python3
"""
NFL Parlay Log Monitor - Automated cleanup and monitoring
Generated by EQ12 System Health Analyzer
"""

from eq12_nfl_parlay_cleanup import NFLParLayLogCleanup
import sys
from datetime import datetime

sys.path.append(r"C:\EQ12\scripts")


def main():
    print(f"{datetime.now()} - NFL Parlay Log Monitor starting...")

    cleanup = NFLParLayLogCleanup()

    # Scan current state
    scan_results = cleanup.scan_nfl_logs()

    # If too many files, run cleanup
    if scan_results["total_files"] > 25:
        print(f"Too many NFL logs ({scan_results['total_files']}), running cleanup...")
        cleanup_results = cleanup.cleanup_excessive_logs(scan_results)
        print(f"Cleanup complete: {cleanup_results['files_removed']} removed")
    else:
        print(f"NFL logs within limits ({scan_results['total_files']} files)")

    print(f"{datetime.now()} - NFL Parlay Log Monitor complete")


if __name__ == "__main__":
    main()
