#!/usr/bin/env python3
"""
Automatic NFL Parlay Log Rotation
Generated by EQ12 NFL Logging Frequency Optimizer
"""

import gzip
import shutil
from datetime import datetime
from pathlib import Path


def rotate_nfl_logs():
    logs_dir = Path("C:/EQ12/logs")
    archive_dir = logs_dir / "archive" / "nfl_parlay"
    archive_dir.mkdir(parents=True, exist_ok=True)

    # Find NFL parlay logs
    nfl_logs = list(logs_dir.glob("*nfl*parlay*.log")) + \
        list(logs_dir.glob("*nfl*parlay*.json"))

    # Keep only the most recent 25 files
    nfl_logs.sort(key=lambda f: f.stat().st_mtime, reverse=True)

    files_to_archive = nfl_logs[25:]

    for log_file in files_to_archive:
        try:
            # Check file size
            size_mb = log_file.stat().st_size / (1024 * 1024)

            if size_mb > 5:
                # Compress and archive large files
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                archive_name = f"{log_file.stem}_{timestamp}.gz"
                archive_path = archive_dir / archive_name

                with open(log_file, "rb") as f_in:
                    with gzip.open(archive_path, "wb") as f_out:
                        shutil.copyfileobj(f_in, f_out)

                log_file.unlink()
                print(f"Archived and compressed: {log_file.name} -> {archive_name}")
            else:
                # Just move smaller files
                timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
                archive_name = f"{log_file.stem}_{timestamp}{log_file.suffix}"
                archive_path = archive_dir / archive_name

                shutil.move(str(log_file), str(archive_path))
                print(f"Archived: {log_file.name} -> {archive_name}")

        except Exception as e:
            print(f"Error archiving {log_file}: {e}")

    print(f"Log rotation complete - processed {len(files_to_archive)} files")


if __name__ == "__main__":
    rotate_nfl_logs()
