#!/bin/bash
# ================================
# EQ12 WSL .bashrc Fix Script
# Replaces interactive .bashrc that freezes VS Code Remote
# ================================

set -e

echo "🔧 EQ12 WSL .bashrc Fix Script"
echo "================================"

# Backup existing .bashrc
if [ -f "$HOME/.bashrc" ]; then
    BACKUP="$HOME/.bashrc.backup_$(date +%Y%m%d_%H%M%S)"
    cp "$HOME/.bashrc" "$BACKUP"
    echo "✅ Backed up existing .bashrc to: $BACKUP"
fi

# Create safe .bashrc
cat > "$HOME/.bashrc" << 'EOF'
# ---- SAFE .bashrc for VS Code + WSL + DevContainers ----
# Generated by EQ12 WSL Fix Script
# Date: $(date)

# Prevent interactive prompts that break VS Code Remote
export DEBIAN_FRONTEND=noninteractive

# Ensure local binaries work
export PATH="$HOME/.local/bin:$PATH"

# Python UTF-8 mode (prevents encoding errors)
export PYTHONUTF8=1
export LC_ALL=C.UTF-8
export LANG=C.UTF-8

# EQ12 environment variables (add your keys here)
# export GROQ_API_KEY="your-key-here"
# export OPENAI_API_KEY="your-key-here"
# export ODDS_API_KEY="your-key-here"
# export TELEGRAM_BOT_TOKEN="your-token-here"
# export TELEGRAM_CHAT_ID="your-chat-id-here"

# Git configuration
export GIT_EDITOR=nano

# Basic shell settings (non-interactive)
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# DO NOT ADD BELOW THIS LINE:
# - conda init
# - nvm init
# - pyenv init
# - docker init
# - any read -p commands
# - any menus or banners
# - any EQ12 auto-start scripts
# These WILL freeze VS Code Remote and DevContainers
EOF

echo "✅ Created safe .bashrc at: $HOME/.bashrc"

# Create safe .bash_profile (if needed)
if [ ! -f "$HOME/.bash_profile" ]; then
    cat > "$HOME/.bash_profile" << 'EOF'
# Load .bashrc for login shells
if [ -f "$HOME/.bashrc" ]; then
    . "$HOME/.bashrc"
fi
EOF
    echo "✅ Created .bash_profile"
fi

# Create safe .profile
cat > "$HOME/.profile" << 'EOF'
# Safe .profile for VS Code Remote
if [ -n "$BASH_VERSION" ]; then
    if [ -f "$HOME/.bashrc" ]; then
        . "$HOME/.bashrc"
    fi
fi
EOF
echo "✅ Created safe .profile"

echo ""
echo "🎯 Next steps:"
echo "1. Exit this shell: exit"
echo "2. Shutdown WSL: wsl --shutdown (from Windows PowerShell)"
echo "3. Reopen VS Code and connect to WSL"
echo "4. VS Code Remote should now load without freezing"
echo ""
echo "✅ .bashrc fix complete!"
