#!/usr/bin/env python3
"""
Sports Telegram Dispatcher
Sends sports picks and analysis to Telegram
"""
from __future__ import annotations

import sys
from datetime import datetime

import requests

from eq12_shared import CredentialError, CredentialManager

credential_manager = CredentialManager()


def resolve_credentials(args: list[str]) -> tuple[str, str]:
    if len(args) >= 2 and args[0] and args[1]:
        return args[0], args[1]
    token = credential_manager.ensure_env(
        "telegram.bot_token",
        "TELEGRAM_BOT_TOKEN",
        prompt="Enter Telegram bot token: ",
        mask_input=True,
    )
    chat_id = credential_manager.ensure_env(
        "telegram.chat_id",
        "TELEGRAM_CHAT_ID",
        prompt="Enter Telegram chat id: ",
        mask_input=False,
    )
    return token, chat_id


def send_telegram_message(token: str, chat_id: str, message: str, *, attempt: int = 1) -> bool:
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    data = {"chat_id": chat_id, "text": message, "parse_mode": "Markdown"}
    response = requests.post(url, json=data, timeout=10)
    if response.status_code == 200:
        return True

    lowered = response.text.lower()
    if attempt < 2:
        if response.status_code in {401, 403}:
            credential_manager.invalidate(
                "telegram.bot_token",
                prompt="Telegram bot token invalid. Enter a new token: ",
                mask_input=True,
            )
            new_token, _ = resolve_credentials([])
            return send_telegram_message(new_token, chat_id, message, attempt=attempt + 1)
        if response.status_code == 400 and "chat" in lowered and "not found" in lowered:
            credential_manager.invalidate(
                "telegram.chat_id",
                prompt="Telegram chat id invalid. Enter a new chat id: ",
                mask_input=False,
            )
            _, new_chat_id = resolve_credentials([])
            return send_telegram_message(token, new_chat_id, message, attempt=attempt + 1)
    print(f"Telegram API error {response.status_code}: {response.text}")
    return False


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: sports_telegram.py <action_text> [bot_token] [chat_id]")
        return 1

    action_text = sys.argv[1]

    try:
        bot_token, chat_id = resolve_credentials(sys.argv[2:])
    except CredentialError as err:
        print(f"Credential error: {err}")
        return 1

    message = f"""
�Y?+ **EQ12 SPORTS ALERT**
�Y". {datetime.now().strftime('%Y-%m-%d %H:%M')}

�YZ_ **Action Required:**
{action_text}

�Y" *Generated by EQ12 God Mode Commander*
"""

    if send_telegram_message(bot_token, chat_id, message):
        print("�o. Sports alert sent to Telegram successfully")
        return 0
    print("❌ Failed to send Telegram message")
    return 1


if __name__ == "__main__":
    sys.exit(main())
